words = [
    {"pl": "dorosły", "en": "adult", "category": "Człowiek"},
    {"pl": "wiek", "en": "age", "category": "Człowiek"},
    {"pl": "urodzony(urodzić się)", "en": "born(be born)", "category": "Człowiek"},
    {"pl": "data urodzenia", "en": "date of birth", "category": "Człowiek"},
    {"pl": "rodzina", "en": "Family", "category": "Człowiek"},
    {"pl": "dom", "en": "home", "category": "Człowiek"},
    {"pl": "tożsamość", "en": "identity", "category": "Człowiek"},
    {"pl": "zainteresowania", "en": "interests", "category": "Człowiek"},
    {"pl": "mężczyzna", "en": "man", "category": "Człowiek"},
    {"pl": "żonaty", "en": "married", "category": "Człowiek"},
    {"pl": "imię", "en": "name", "category": "Człowiek"},
    {"pl": "narodowość", "en": "nationality", "category": "Człowiek"},
    {"pl": "młody", "en": "young", "category": "Człowiek"},
    {"pl": "kobieta", "en": "woman", "category": "Człowiek"},
    {"pl": "nastolatek/nastolatka", "en": "teenager", "category": "Człowiek"},
    {"pl": "nazwisko", "en": "surname", "category": "Człowiek"},
    {"pl": "stary", "en": "old", "category": "Człowiek"},
    {"pl": "przydomek,przezwisko", "en": "nickname", "category": "Człowiek"},
    {"pl": "aktywny", "en": "active", "category": "Człowiek"},
    {"pl": "agresywny", "en": "aggressive", "category": "Człowiek"},
    {"pl": "ambitny", "en": "ambitious", "category": "Człowiek"},
    {"pl": "zły", "en": "bad", "category": "Człowiek"},
    {"pl": "wybuchowy", "en": "bad-tempered", "category": "Człowiek"},
    {"pl": "zrównoważony", "en": "balanced", "category": "Człowiek"},
    {"pl": "apodyktyczny", "en": "bossy", "category": "Człowiek"},
    {"pl": "dzielny,odważny", "en": "brave", "category": "Człowiek"},
    {"pl": "ostrożny", "en": "careful", "category": "Człowiek"},
    {"pl": "dbający,troskliwy", "en": "caring", "category": "Człowiek"},
    {"pl": "radosny", "en": "cheerful", "category": "Człowiek"},
    {"pl": "dziecinny", "en": "childish", "category": "Człowiek"},
    {"pl": "zdolny, bystry", "en": "clever", "category": "Człowiek"},
    {"pl": "pewny siebie", "en": "confident", "category": "Człowiek"},
    {"pl": "twórczy", "en": "creative", "category": "Człowiek"},
    {"pl": "pełen energii", "en": "energetic", "category": "Człowiek"},
    {"pl": "sprawiedliwy", "en": "fair", "category": "Człowiek"},
    {"pl": "przyjazny", "en": "friendly", "category": "Człowiek"},
    {"pl": "zabawny,śmieszny", "en": "funny", "category": "Człowiek"},
    {"pl": "hojny", "en": "generous", "category": "Człowiek"},
    {"pl": "pracowity", "en": "hard-working", "category": "Człowiek"},
    {"pl": "pomocny", "en": "helpful", "category": "Człowiek"},
    {"pl": "uczciwy", "en": "honest", "category": "Człowiek"},
    {"pl": "niecierpliwy", "en": "impatient", "category": "Człowiek"},
    {"pl": "nieuprzejmy,niegrzeczny", "en": "impolite", "category": "Człowiek"},
    {"pl": "popędliwy", "en": "impulsive", "category": "Człowiek"},
    {"pl": "nieliczący się z innymi", "en": "inconsiderate", "category": "Człowiek"},
    {"pl": "inteligentny", "en": "intelligent", "category": "Człowiek"},
    {"pl": "interesujący", "en": "interesting", "category": "Człowiek"},
    {"pl": "nieodpowiedzialny", "en": "irresponsible", "category": "Człowiek"},
    {"pl": "uprzejmy", "en": "kind", "category": "Człowiek"},
    {"pl": "leniwy", "en": "lazy", "category": "Człowiek"},
    {"pl": "żywy,żywiołowy", "en": "lively", "category": "Człowiek"},
    {"pl": "lojalny", "en": "loyal", "category": "Człowiek"},
    {"pl": "mający szczęście", "en": "lucky", "category": "Człowiek"},
    {"pl": "skąpy, złośliwy", "en": "mean", "category": "Człowiek"},
    {"pl": "nieszczęśliwy", "en": "miserable", "category": "Człowiek"},
    {"pl": "humorzasty", "en": "moody", "category": "Człowiek"},
    {"pl": "niemiły", "en": "nasty", "category": "Człowiek"},
    {"pl": "niegrzeczny", "en": "naughty", "category": "Człowiek"},
    {"pl": "miły", "en": "nice", "category": "Człowiek"},
    {"pl": "optymista", "en": "optimist", "category": "Człowiek"},
    {"pl": "optymistyczny", "en": "optimistic", "category": "Człowiek"},
    {"pl": "cierpliwy", "en": "patient", "category": "Człowiek"},
    {"pl": "osobowość", "en": "personality", "category": "Człowiek"},
    {"pl": "pesymista, pesymistka", "en": "pessimist", "category": "Człowiek"},
    {"pl": "grzeczny, uprzejmy", "en": "polite", "category": "Człowiek"},
    {"pl": "praktyczny", "en": "practical", "category": "Człowiek"},
    {"pl": "realista", "en": "realist", "category": "Człowiek"},
    {"pl": "godny zaufania", "en": "reliable", "category": "Człowiek"},
    {"pl": "odpowiedzialny", "en": "responsible", "category": "Człowiek"},
    {"pl": "romantyczny", "en": "romantic", "category": "Człowiek"},
    {"pl": "smutny", "en": "sad", "category": "Człowiek"},
    {"pl": "samolubny", "en": "selfish", "category": "Człowiek"},
    {"pl": "atrakcyjny", "en": "attractive", "category": "Człowiek"},
    {"pl": "łysy", "en": "bald", "category": "Człowiek"},
    {"pl": "broda", "en": "beard", "category": "Człowiek"},
    {"pl": "piękny", "en": "beautiful", "category": "Człowiek"},
    {"pl": "budowa", "en": "built", "category": "Człowiek"},
    {"pl": "opis", "en": "description", "category": "Człowiek"},
    {"pl": "gruby", "en": "fat", "category": "Człowiek"},
    {"pl": "sprawny, w dobrej formie", "en": "fit", "category": "Człowiek"},
    {"pl": "piegi", "en": "freckles", "category": "Człowiek"},
    {"pl": "atrakcyjny,przystojny", "en": "good-looking", "category": "Człowiek"},
    {"pl": "włosy", "en": "hair", "category": "Człowiek"},
    {"pl": "włosy kręcone", "en": "curly hair", "category": "Człowiek"},
    {"pl": "włosy ciemne", "en": "dark hair", "category": "Człowiek"},
    {"pl": "włosy długie", "en": "long hair", "category": "Człowiek"},
    {"pl": "włosy proste", "en": "straight hair", "category": "Człowiek"},
    {"pl": "włosy falujące", "en": "wavy hair", "category": "Człowiek"},
    {"pl": "fryzura", "en": "hairstyle", "category": "Człowiek"},
    {"pl": "przystojny", "en": "handsome", "category": "Człowiek"},
    {"pl": "wzrost", "en": "height", "category": "Człowiek"},
    {"pl": "wyglądać jak", "en": "look like", "category": "Człowiek"},
    {"pl": "makijaż", "en": "make-up", "category": "Człowiek"},
    {"pl": "wąsy", "en": "moustache", "category": "Człowiek"},
    {"pl": "nadwaga", "en": "overweight", "category": "Człowiek"},
    {"pl": "śliczny", "en": "pretty", "category": "Człowiek"},
    {"pl": "blizna", "en": "scar", "category": "Człowiek"},
    {"pl": "niski,krótki", "en": "short", "category": "Człowiek"},
    {"pl": "podobny", "en": "similar", "category": "Człowiek"},
    {"pl": "szczupły", "en": "slim", "category": "Człowiek"},
    {"pl": "uśmiechać się", "en": "smile", "category": "Człowiek"},
    {"pl": "wysportowany", "en": "sporty", "category": "Człowiek"},
    {"pl": "wysoki", "en": "tall", "category": "Człowiek"},
    {"pl": "tatuaż", "en": "tattoo", "category": "Człowiek"},
    {"pl": "cienki,chudy", "en": "thin", "category": "Człowiek"},
    {"pl": "znany", "en": "well-known", "category": "Człowiek"},
    {"pl": "dziwny", "en": "weird", "category": "Człowiek"},
    {"pl": "pełen przemocy", "en": "violent", "category": "Człowiek"},
    {"pl": "czuły", "en": "tender", "category": "Człowiek"},
    {"pl": "głupi", "en": "stupid", "category": "Człowiek"},
    {"pl": "nieśmiały", "en": "shy", "category": "Człowiek"},
    {"pl": "poważny", "en": "serious", "category": "Człowiek"},
    {"pl": "wrażliwy", "en": "sensitive", "category": "Człowiek"},
    {"pl": "rozsądny", "en": "sensible", "category": "Człowiek"},
    {"pl": "podziwiać", "en": "admire", "category": "Człowiek"},
    {"pl": "uwielbiać", "en": "adore", "category": "Człowiek"},
    {"pl": "zły", "en": "angry", "category": "Człowiek"},
    {"pl": "zirytowany", "en": "annoyed", "category": "Człowiek"},
    {"pl": "znudzony", "en": "bored", "category": "Człowiek"},
    {"pl": "spokojny", "en": "calm", "category": "Człowiek"},
    {"pl": "zrelaksowany,odprężony", "en": "chilled", "category": "Człowiek"},
    {"pl": "zmieszany", "en": "confused", "category": "Człowiek"},
    {"pl": "zły", "en": "cross", "category": "Człowiek"},
    {"pl": "przygnębiony", "en": "depressed", "category": "Człowiek"},
    {"pl": "rozczarowany", "en": "disappointed", "category": "Człowiek"},
    {"pl": "nie lubić", "en": "dislike", "category": "Człowiek"},
    {"pl": "wzruszenie,emocja", "en": "emotion", "category": "Człowiek"},
    {"pl": "podekscytowany", "en": "excited", "category": "Człowiek"},
    {"pl": "mieć ochotę", "en": "fancy", "category": "Człowiek"},
    {"pl": "czuć", "en": "feel", "category": "Człowiek"},
    {"pl": "zostawać", "en": "stay", "category": "Dom"},
{"pl": "dzielić", "en": "share", "category": "Dom"},
{"pl": "sprzedawać", "en": "sell", "category": "Dom"},
{"pl": "wynająć", "en": "rent", "category": "Dom"},
{"pl": "malować", "en": "decorate", "category": "Dom"},
{"pl": "kupować", "en": "buy", "category": "Dom"},
{"pl": "tradycyjny", "en": "traditional", "category": "Dom"},
{"pl": "niezwykły", "en": "unusual", "category": "Dom"},
{"pl": "barka", "en": "barge", "category": "Dom"},
{"pl": "blok mieszkalny", "en": "block of flats", "category": "Dom"},
{"pl": "dom parterowy", "en": "bungalow", "category": "Dom"},
{"pl": "samochód kempingowy", "en": "camper van", "category": "Dom"},
{"pl": "przyczepa kempingowa", "en": "caravan", "category": "Dom"},
{"pl": "zamek", "en": "castle", "category": "Dom"},
{"pl": "mieszkanie", "en": "flat", "category": "Dom"},
{"pl": "domek letni", "en": "holiday home", "category": "Dom"},
{"pl": "dom", "en": "house", "category": "Dom"},
{"pl": "rezydencja", "en": "mansion", "category": "Dom"},
{"pl": "namiot", "en": "tent", "category": "Dom"},
{"pl": "willa", "en": "villa", "category": "Dom"},
{"pl": "dom na drzewie", "en": "tree house", "category": "Dom"},
{"pl": "kolorowy", "en": "colourful", "category": "Dom"},
{"pl": "wygodny", "en": "comfortable", "category": "Dom"},
{"pl": "ogromny", "en": "enormous", "category": "Dom"},
{"pl": "drogi", "en": "expensive", "category": "Dom"},
{"pl": "nowoczesny", "en": "modern", "category": "Dom"},
{"pl": "bliski", "en": "near", "category": "Dom"},
{"pl": "głośny", "en": "noisy", "category": "Dom"},
{"pl": "zwykły, zwyczajny", "en": "ordinary", "category": "Dom"},
{"pl": "spokojny", "en": "peaceful", "category": "Dom"},
{"pl": "plakat", "en": "poster", "category": "Dom"},
{"pl": "grzejnik", "en": "radiator", "category": "Dom"},
{"pl": "pokój", "en": "room", "category": "Dom"},
{"pl": "półka", "en": "shelf", "category": "Dom"},
{"pl": "prysznic", "en": "shower", "category": "Dom"},
{"pl": "zlew", "en": "sink", "category": "Dom"},
{"pl": "kanapa", "en": "sofa", "category": "Dom"},
{"pl": "schody", "en": "stairs", "category": "Dom"},
{"pl": "gabinet", "en": "study", "category": "Dom"},
{"pl": "stół", "en": "table", "category": "Dom"},
{"pl": "toaleta", "en": "toilet", "category": "Dom"},
{"pl": "wazon", "en": "vase", "category": "Dom"},
{"pl": "szafa", "en": "wardrobe", "category": "Dom"},
{"pl": "pralka", "en": "washing machine", "category": "Dom"},
{"pl": "rzeźba", "en": "sculpture", "category": "Dom"},
{"pl": "fotel", "en": "armchair", "category": "Dom"},
{"pl": "balkon", "en": "balcony", "category": "Dom"},
{"pl": "wanna", "en": "bath", "category": "Dom"},
{"pl": "łazienka", "en": "bathroom", "category": "Dom"},
{"pl": "łóżko", "en": "bed", "category": "Dom"},
{"pl": "sypialnia", "en": "bedroom", "category": "Dom"},
{"pl": "szafka nocna", "en": "bedside table", "category": "Dom"},
{"pl": "regał na książki", "en": "bookcase", "category": "Dom"},
{"pl": "dywan", "en": "carpet", "category": "Dom"},
{"pl": "kuchenka", "en": "cooker", "category": "Dom"},
{"pl": "zasłona", "en": "curtain", "category": "Dom"},
{"pl": "biurko", "en": "desk", "category": "Dom"},
{"pl": "jadalnia", "en": "dining room", "category": "Dom"},
{"pl": "zmywarka do naczyń", "en": "dishwasher", "category": "Dom"},
{"pl": "pierwsze piętro", "en": "first floor", "category": "Dom"},
{"pl": "zamrażarka", "en": "freezer", "category": "Dom"},
{"pl": "lodówka", "en": "fridge", "category": "Dom"},
{"pl": "umeblowany", "en": "furnished", "category": "Dom"},
{"pl": "garaż", "en": "garage", "category": "Dom"},
{"pl": "ogród", "en": "garden", "category": "Dom"},
{"pl": "hol", "en": "hall", "category": "Dom"},
{"pl": "dom,mieszkanie", "en": "home", "category": "Dom"},
{"pl": "kuchnia", "en": "kitchen", "category": "Dom"},
{"pl": "lampa", "en": "lamp", "category": "Dom"},
{"pl": "winda", "en": "lift, elevator", "category": "Dom"},
{"pl": "zawsze", "en": "always", "category": "Życie rodzinne i towarzyskie"},
{"pl": "w tej chwili", "en": "at the moment", "category": "Życie rodzinne i towarzyskie"},
{"pl": "w weekend", "en": "at the weekend", "category": "Życie rodzinne i towarzyskie"},
{"pl": "codziennie", "en": "every day", "category": "Życie rodzinne i towarzyskie"},
{"pl": "po południu", "en": "in the afternoon", "category": "Życie rodzinne i towarzyskie"},
{"pl": "wieczorem", "en": "in the evening", "category": "Życie rodzinne i towarzyskie"},
{"pl": "rano", "en": "in the morning", "category": "Życie rodzinne i towarzyskie"},
{"pl": "nigdy", "en": "never", "category": "Życie rodzinne i towarzyskie"},
{"pl": "noc", "en": "night", "category": "Życie rodzinne i towarzyskie"},
{"pl": "często", "en": "often", "category": "Życie rodzinne i towarzyskie"},
{"pl": "raz w tygodniu", "en": "once a week", "category": "Życie rodzinne i towarzyskie"},
{"pl": "rzadko", "en": "rarely", "category": "Życie rodzinne i towarzyskie"},
{"pl": "czasami", "en": "sometimes", "category": "Życie rodzinne i towarzyskie"},
{"pl": "dzisiaj", "en": "today", "category": "Życie rodzinne i towarzyskie"},
{"pl": "dziś wieczorem", "en": "tonight", "category": "Życie rodzinne i towarzyskie"},
{"pl": "zwykle", "en": "usually", "category": "Życie rodzinne i towarzyskie"},
{"pl": "szczotkować", "en": "brush", "category": "Życie rodzinne i towarzyskie"},
{"pl": "czyścić", "en": "clean", "category": "Życie rodzinne i towarzyskie"},
{"pl": "ubierać się", "en": "get dressed", "category": "Życie rodzinne i towarzyskie"},
{"pl": "wracać do domu", "en": "get home", "category": "Życie rodzinne i towarzyskie"},
{"pl": "wstawać", "en": "get up", "category": "Życie rodzinne i towarzyskie"},
{"pl": "iść", "en": "go", "category": "Życie rodzinne i towarzyskie"},
{"pl": "iść do domu", "en": "go home", "category": "Życie rodzinne i towarzyskie"},
{"pl": "iść spać", "en": "go to bed", "category": "Życie rodzinne i towarzyskie"},
{"pl": "iść do szkoły", "en": "go to school", "category": "Życie rodzinne i towarzyskie"},
{"pl": "iść do pracy", "en": "go to work", "category": "Życie rodzinne i towarzyskie"},
{"pl": "jeść śniadanie", "en": "have breakfast", "category": "Życie rodzinne i towarzyskie"},
{"pl": "jeść obiad", "en": "have dinner", "category": "Życie rodzinne i towarzyskie"},
{"pl": "jeść lunch", "en": "have lunch", "category": "Życie rodzinne i towarzyskie"},
{"pl": "praca domowa", "en": "homework", "category": "Życie rodzinne i towarzyskie"},
{"pl": "robić obiad", "en": "make dinner", "category": "Życie rodzinne i towarzyskie"},
{"pl": "ścielić łóżko", "en": "make one's bed", "category": "Życie rodzinne i towarzyskie"},
{"pl": "odpoczywać", "en": "relax", "category": "Życie rodzinne i towarzyskie"},
{"pl": "spać", "en": "sleep", "category": "Życie rodzinne i towarzyskie"},
{"pl": "zostać w domu", "en": "stay(at) home", "category": "Życie rodzinne i towarzyskie"},
{"pl": "uczyć się", "en": "study", "category": "Życie rodzinne i towarzyskie"},
{"pl": "budzić(się)", "en": "wake(up)", "category": "Życie rodzinne i towarzyskie"},
{"pl": "spacerować", "en": "walk", "category": "Życie rodzinne i towarzyskie"},
{"pl": "prać, myć", "en": "wash", "category": "Życie rodzinne i towarzyskie"},
{"pl": "oglądać", "en": "watch", "category": "Życie rodzinne i towarzyskie"},
{"pl": "przychodzić z wizytą", "en": "come round", "category": "Życie rodzinne i towarzyskie"},
{"pl": "odrabiać prace domową", "en": "do homework", "category": "Życie rodzinne i towarzyskie"},
{"pl": "robić zakupy", "en": "do the shopping", "category": "Życie rodzinne i towarzyskie"},
{"pl": "iść na spacer", "en": "go for a walk", "category": "Życie rodzinne i towarzyskie"},
{"pl": "jechać na wakacje", "en": "go on holiday", "category": "Życie rodzinne i towarzyskie"},
{"pl": "iść na zakupy", "en": "go shopping", "category": "Życie rodzinne i towarzyskie"},
{"pl": "iść pływać", "en": "go swimming", "category": "Życie rodzinne i towarzyskie"},
{"pl": "iść do kina", "en": "go to the cinema", "category": "Życie rodzinne i towarzyskie"},
{"pl": "przesiadywać", "en": "hang out", "category": "Życie rodzinne i towarzyskie"},
{"pl": "jazda konna", "en": "horse riding", "category": "Życie rodzinne i towarzyskie"},
{"pl": "zapisać się do klubu", "en": "join a club", "category": "Życie rodzinne i towarzyskie"},
{"pl": "słuchać muzyki", "en": "listen to music", "category": "Życie rodzinne i towarzyskie"},
{"pl": "przyjaciele", "en": "friends", "category": "Życie rodzinne i towarzyskie"},
{"pl": "spotykać przyjaciół", "en": "meet friends", "category": "Życie rodzinne i towarzyskie"},
{"pl": "dzwonić do przyjaciół", "en": "phone friends", "category": "Życie rodzinne i towarzyskie"},
{"pl": "odwiedzać przyjaciół", "en": "visit friends", "category": "Życie rodzinne i towarzyskie"},
{"pl": "poznać, spotykać ludzi", "en": "meet people", "category": "Życie rodzinne i towarzyskie"},
{"pl": "grać", "en": "play", "category": "Życie rodzinne i towarzyskie"},
{"pl": "grać na instrumencie", "en": "play a musical", "category": "Życie rodzinne i towarzyskie"},
{"pl": "muzycznym", "en": "instrument", "category": "Życie rodzinne i towarzyskie"},
{"pl": "grać w szachy", "en": "play chess", "category": "Życie rodzinne i towarzyskie"},
{"pl": "grać w piłkę nożną", "en": "play football", "category": "Życie rodzinne i towarzyskie"},
{"pl": "grać na gitarze", "en": "play the guitar", "category": "Życie rodzinne i towarzyskie"},
{"pl": "czytać", "en": "read", "category": "Życie rodzinne i towarzyskie"},
{"pl": "czytać książki", "en": "read books", "category": "Życie rodzinne i towarzyskie"},
{"pl": "czytać czasopisma", "en": "read magazines", "category": "Życie rodzinne i towarzyskie"},
{"pl": "jeździć na rowerze", "en": "ride a bicycle", "category": "Życie rodzinne i towarzyskie"},
{"pl": "wysyłać", "en": "send", "category": "Życie rodzinne i towarzyskie"},
{"pl": "surfować w internecie", "en": "surf the internet", "category": "Życie rodzinne i towarzyskie"},
{"pl": "zacząć coś regularnie robić", "en": "take sth up", "category": "Życie rodzinne i towarzyskie"},
{"pl": "opowiadać dowcip", "en": "tell a joke", "category": "Życie rodzinne i towarzyskie"},
{"pl": "spacerować", "en": "walk around", "category": "Życie rodzinne i towarzyskie"},
{"pl": "iść pieszo do domu", "en": "walk home", "category": "Życie rodzinne i towarzyskie"},
{"pl": "oglądać telewizje", "en": "watch TV", "category": "Życie rodzinne i towarzyskie"},
{"pl": "rocznica", "en": "anniversary", "category": "Życie rodzinne i towarzyskie"},
{"pl": "coroczne święto", "en": "annual holiday", "category": "Życie rodzinne i towarzyskie"},
{"pl": "urodziny", "en": "birthday", "category": "Życie rodzinne i towarzyskie"},
{"pl": "ciasto", "en": "cake", "category": "Życie rodzinne i towarzyskie"},
{"pl": "karnawał", "en": "carnival", "category": "Życie rodzinne i towarzyskie"},
{"pl": "świętować", "en": "celebrate", "category": "Życie rodzinne i towarzyskie"},
{"pl": "uroczystość", "en": "celebration", "category": "Życie rodzinne i towarzyskie"},
{"pl": "ceremonia", "en": "ceremony", "category": "Życie rodzinne i towarzyskie"},
{"pl": "na zdrowie", "en": "cheers", "category": "Życie rodzinne i towarzyskie"},
{"pl": "chrzciny", "en": "christening", "category": "Życie rodzinne i towarzyskie"},
{"pl": "święta Bożego Narodzenia", "en": "Christmas", "category": "Życie rodzinne i towarzyskie"},
{"pl": "kościół", "en": "church", "category": "Życie rodzinne i towarzyskie"},
{"pl": "kostium", "en": "costume", "category": "Życie rodzinne i towarzyskie"},
{"pl": "tańczyć", "en": "dance", "category": "Życie rodzinne i towarzyskie"},
{"pl": "przebierać się", "en": "dress up", "category": "Życie rodzinne i towarzyskie"},
{"pl": "Wielkanoc", "en": "Easter", "category": "Życie rodzinne i towarzyskie"},
{"pl": "festiwal,święto", "en": "festival", "category": "Życie rodzinne i towarzyskie"},
{"pl": "sztuczne ognie, fajerwerki", "en": "fireworks", "category": "Życie rodzinne i towarzyskie"},
{"pl": "gość", "en": "guest", "category": "Życie rodzinne i towarzyskie"},
{"pl": "maska", "en": "mask", "category": "Życie rodzinne i towarzyskie"},
{"pl": "suknia ślubna", "en": "wedding dress", "category": "Życie rodzinne i towarzyskie"},
{"pl": "ślub,wesele", "en": "wedding", "category": "Życie rodzinne i towarzyskie"},
{"pl": "ciotka", "en": "aunt", "category": "Życie rodzinne i towarzyskie"},
{"pl": "brat", "en": "brother", "category": "Życie rodzinne i towarzyskie"},
{"pl": "kuzyn", "en": "cousin", "category": "Życie rodzinne i towarzyskie"},
{"pl": "tata", "en": "dad", "category": "Życie rodzinne i towarzyskie"},
{"pl": "córka", "en": "daughter", "category": "Życie rodzinne i towarzyskie"},
{"pl": "rozwiedziony", "en": "divorced", "category": "Życie rodzinne i towarzyskie"},
{"pl": "były mąż", "en": "ex-husband", "category": "Życie rodzinne i towarzyskie"},
{"pl": "była żona", "en": "ex-wife", "category": "Życie rodzinne i towarzyskie"},
{"pl": "rodzina", "en": "Family", "category": "Życie rodzinne i towarzyskie"},
{"pl": "drzewo genealogiczne", "en": "Family tree", "category": "Życie rodzinne i towarzyskie"},
{"pl": "ojciec", "en": "father", "category": "Życie rodzinne i towarzyskie"},
{"pl": "narzeczony", "en": "fiancé", "category": "Życie rodzinne i towarzyskie"},
{"pl": "narzeczona", "en": "fiancée", "category": "Życie rodzinne i towarzyskie"},
{"pl": "wnuczka", "en": "granddaughter", "category": "Życie rodzinne i towarzyskie"},
{"pl": "dziadek", "en": "grandfather", "category": "Życie rodzinne i towarzyskie"},
{"pl": "babcia", "en": "grandmother", "category": "Życie rodzinne i towarzyskie"},
{"pl": "wnuk", "en": "grandson", "category": "Życie rodzinne i towarzyskie"},
{"pl": "mąż", "en": "husband", "category": "Życie rodzinne i towarzyskie"},
{"pl": "młodsza siostra", "en": "little sister", "category": "Życie rodzinne i towarzyskie"},
{"pl": "matka", "en": "mother", "category": "Życie rodzinne i towarzyskie"},
{"pl": "mama", "en": "mum", "category": "Życie rodzinne i towarzyskie"},
{"pl": "siostrzeniec, bratanek", "en": "nephew", "category": "Życie rodzinne i towarzyskie"},
{"pl": "siostrzenica,bratanica", "en": "niece", "category": "Życie rodzinne i towarzyskie"},
{"pl": "rodzic", "en": "parent", "category": "Życie rodzinne i towarzyskie"},
{"pl": "krewny", "en": "relative", "category": "Życie rodzinne i towarzyskie"},
{"pl": "siostra", "en": "sister", "category": "Życie rodzinne i towarzyskie"},
{"pl": "syn", "en": "son", "category": "Życie rodzinne i towarzyskie"},
{"pl": "przyrodni brat", "en": "stepbrother", "category": "Życie rodzinne i towarzyskie"},
{"pl": "ojczym", "en": "stepfather", "category": "Życie rodzinne i towarzyskie"},
{"pl": "macocha", "en": "stepmother", "category": "Życie rodzinne i towarzyskie"},
{"pl": "przyrodnia siostra", "en": "stepsister", "category": "Życie rodzinne i towarzyskie"},
{"pl": "bliźniak/bliźniaczka", "en": "twin", "category": "Życie rodzinne i towarzyskie"},
{"pl": "wujek", "en": "uncle", "category": "Życie rodzinne i towarzyskie"},
{"pl": "obowiązkowy", "en": "compulsory", "category": "Szkoła"},
{"pl": "program nauczania", "en": "curriculum", "category": "Szkoła"},
{"pl": "wykształcenie", "en": "education", "category": "Szkoła"},
{"pl": "egzamin", "en": "exam", "category": "Szkoła"},
{"pl": "zdać egzamin", "en": "pass an exam", "category": "Szkoła"},
{"pl": "ćwiczenie", "en": "exercise", "category": "Szkoła"},
{"pl": "rok przerwy między szkoła a studiami", "en": "gap year", "category": "Szkoła"},
{"pl": "praca domowa", "en": "homework", "category": "Szkoła"},
{"pl": "lekcja", "en": "lesson", "category": "Szkoła"},
{"pl": "zadanie, projekt", "en": "project", "category": "Szkoła"},
{"pl": "szkoła", "en": "school", "category": "Szkoła"},
{"pl": "szkoła podstawowa", "en": "primary school", "category": "Szkoła"},
{"pl": "szkoła państwowa", "en": "state school", "category": "Szkoła"},
{"pl": "szkoła średnia", "en": "secondary school", "category": "Szkoła"},
{"pl": "student, uczeń", "en": "student", "category": "Szkoła"},
{"pl": "przedmiot", "en": "subject", "category": "Szkoła"},
{"pl": "semestr", "en": "term", "category": "Szkoła"},
{"pl": "test, klasówka, sprawdzian", "en": "test", "category": "Szkoła"},
{"pl": "rozkład zajęć", "en": "timetable", "category": "Szkoła"},
{"pl": "uniwersytet", "en": "university", "category": "Szkoła"},
{"pl": "algebra", "en": "algebra", "category": "Szkoła"},
{"pl": "plastyka", "en": "art", "category": "Szkoła"},
{"pl": "biologia", "en": "biology", "category": "Szkoła"},
{"pl": "chemia", "en": "chemistry", "category": "Szkoła"},
{"pl": "projektowanie", "en": "design", "category": "Szkoła"},
{"pl": "zajęcia teatralne", "en": "drama", "category": "Szkoła"},
{"pl": "angielski", "en": "English", "category": "Szkoła"},
{"pl": "język obcy", "en": "foreign language", "category": "Szkoła"},
{"pl": "francuski", "en": "French", "category": "Szkoła"},
{"pl": "geografia", "en": "geography", "category": "Szkoła"},
{"pl": "niemiecki", "en": "German", "category": "Szkoła"},
{"pl": "gimnastyka", "en": "gymnastics", "category": "Szkoła"},
{"pl": "historia", "en": "history", "category": "Szkoła"},
{"pl": "japoński", "en": "Japanese", "category": "Szkoła"},
{"pl": "łacina", "en": "Latin", "category": "Szkoła"},
{"pl": "matematyka", "en": "maths", "category": "Szkoła"},
{"pl": "nauka o mediach", "en": "media studies", "category": "Szkoła"},
{"pl": "muzyka", "en": "music", "category": "Szkoła"},
{"pl": "fizyka", "en": "physics", "category": "Szkoła"},
{"pl": "przedmioty ścisłe", "en": "science", "category": "Szkoła"},
{"pl": "hiszpański", "en": "Spanish", "category": "Szkoła"},
{"pl": "aktorka", "en": "actress", "category": "Praca"},
{"pl": "alchemik", "en": "alchemist", "category": "Praca"},
{"pl": "archeolog", "en": "archaeologist", "category": "Praca"},
{"pl": "artysta/artystka", "en": "artist", "category": "Praca"},
{"pl": "asystent/asystentka", "en": "assistant", "category": "Praca"},
{"pl": "astronauta", "en": "astronaut", "category": "Praca"},
{"pl": "sportowiec", "en": "athlete", "category": "Praca"},
{"pl": "opiekun/opiekunka do dzieci", "en": "babysitter", "category": "Praca"},
{"pl": "urzędnik bankowy", "en": "bank clerk", "category": "Praca"},
{"pl": "bankier", "en": "banker", "category": "Praca"},
{"pl": "biznesmen", "en": "businessman", "category": "Praca"},
{"pl": "szofer", "en": "chauffeur", "category": "Praca"},
{"pl": "szef kuchni", "en": "chef", "category": "Praca"},
{"pl": "komik", "en": "comedian", "category": "Praca"},
{"pl": "kompozytor/kompozytorka", "en": "composer", "category": "Praca"},
{"pl": "inżynier informatyk", "en": "Computer engineer", "category": "Praca"},
{"pl": "dyrygent, konduktor", "en": "conductor", "category": "Praca"},
{"pl": "tancerz", "en": "dancer", "category": "Praca"},
{"pl": "dentysta/dentystka", "en": "dentist", "category": "Praca"},
{"pl": "detektyw", "en": "detective", "category": "Praca"},
{"pl": "dyplomata", "en": "diplomat", "category": "Praca"},
{"pl": "reżyser,dyrektor/dyrektorka", "en": "director", "category": "Praca"},
{"pl": "lekarz/lekarka", "en": "doctor", "category": "Praca"},
{"pl": "ekonomista/ekonomistka", "en": "economist", "category": "Praca"},
{"pl": "redaktor/redaktorka", "en": "editor", "category": "Praca"},
{"pl": "inżynier", "en": "engineer", "category": "Praca"},
{"pl": "projektant/projektantka", "en": "Fashion designer", "category": "Praca"},
{"pl": "strażak", "en": "fireman", "category": "Praca"},
{"pl": "ogrodnik/ogrodniczka", "en": "gardener", "category": "Praca"},
{"pl": "historyk", "en": "historian", "category": "Praca"},
{"pl": "sędzia/sędzina", "en": "judge", "category": "Praca"},
{"pl": "pomocnik kucharza", "en": "kitchen helper", "category": "Praca"},
{"pl": "prawnik/prawniczka", "en": "lawyer", "category": "Praca"},
{"pl": "językoznawca", "en": "linguist", "category": "Praca"},
{"pl": "kierowca ciężarówki", "en": "lorry driver", "category": "Praca"},
{"pl": "magik", "en": "magician", "category": "Praca"},
{"pl": "charakteryzator/charakteryzatorka", "en": "make-up artist", "category": "Praca"},
{"pl": "kierownik/kierowniczka", "en": "manager", "category": "Praca"},
{"pl": "matematyk", "en": "mathematician", "category": "Praca"},
{"pl": "mechanik", "en": "mechanic", "category": "Praca"},
{"pl": "muzyk", "en": "musician", "category": "Praca"},
{"pl": "niania", "en": "nanny", "category": "Praca"},
{"pl": "pielęgniarka/pielęgniarz", "en": "nurse", "category": "Praca"},
{"pl": "malarz/malarka", "en": "painter", "category": "Praca"},
{"pl": "pilot", "en": "pilot", "category": "Praca"},
{"pl": "policjant/policjantka", "en": "police officer", "category": "Praca"},
{"pl": "policjant", "en": "policeman", "category": "Praca"},
{"pl": "policjantka", "en": "policewoman", "category": "Praca"},
{"pl": "polityk", "en": "politician", "category": "Praca"},
{"pl": "recepcjonista/recepcjonistka", "en": "receptionist", "category": "Praca"},
{"pl": "marynarz", "en": "sailor", "category": "Praca"},
{"pl": "naukowiec", "en": "scientist", "category": "Praca"},
{"pl": "sekretarka", "en": "secretary", "category": "Praca"},
{"pl": "służący", "en": "servant", "category": "Praca"},
{"pl": "piosenkarz/piosenkarka", "en": "singer", "category": "Praca"},
{"pl": "chirurg", "en": "surgeon", "category": "Praca"},
{"pl": "taksówkarz", "en": "taxi driver", "category": "Praca"},
{"pl": "nauczyciel/nauczycielka", "en": "teacher", "category": "Praca"},
{"pl": "weterynarz", "en": "vet", "category": "Praca"},
{"pl": "kelner", "en": "waiter", "category": "Praca"},
{"pl": "kelnerka", "en": "waitress", "category": "Praca"},
{"pl": "pisarz/pisarka", "en": "writer", "category": "Praca"},
{"pl": "sklep", "en": "shop", "category": "Praca"},
{"pl": "restauracja", "en": "restaurant", "category": "Praca"},
{"pl": "więzienie", "en": "prison", "category": "Praca"},
{"pl": "poczta", "en": "post office", "category": "Praca"},
{"pl": "biuro", "en": "office", "category": "Praca"},
{"pl": "muzeum", "en": "museum", "category": "Praca"},
{"pl": "biblioteka", "en": "library", "category": "Praca"},
{"pl": "sąd", "en": "law court", "category": "Praca"},
{"pl": "hotel", "en": "hotel", "category": "Praca"},
{"pl": "szpital", "en": "hospital", "category": "Praca"},
{"pl": "księgarnia", "en": "bookshop", "category": "Praca"},
{"pl": "bank", "en": "bank", "category": "Praca"},
{"pl": "galeria sztuki", "en": "art gallery", "category": "Praca"},
{"pl": "lotnisko", "en": "airport", "category": "Praca"},
{"pl": "być zdala od domu", "en": "be away from home", "category": "Praca"},
{"pl": "dzwonić", "en": "call", "category": "Praca"},
{"pl": "prowadzić pojazd", "en": "drive a vehicle", "category": "Praca"},
{"pl": "kształcić ludzi", "en": "educate people", "category": "Praca"},
{"pl": "puszka", "en": "a tin of", "category": "Żywienie"},
{"pl": "łyżka,łyżeczka", "en": "a spoonful of", "category": "Żywienie"},
{"pl": "kawałek", "en": "a slice of", "category": "Żywienie"},
{"pl": "dużo", "en": "a lot of", "category": "Żywienie"},
{"pl": "troszkę", "en": "a little", "category": "Żywienie"},
{"pl": "słoik", "en": "a jar of", "category": "Żywienie"},
{"pl": "kilka", "en": "a few", "category": "Żywienie"},
{"pl": "jabłko", "en": "apple", "category": "Żywienie"},
{"pl": "awokado", "en": "avocado", "category": "Żywienie"},
{"pl": "bekon", "en": "bacon", "category": "Żywienie"},
{"pl": "banan", "en": "banana", "category": "Żywienie"},
{"pl": "fasola", "en": "bean", "category": "Żywienie"},
{"pl": "wołowina", "en": "beef", "category": "Żywienie"},
{"pl": "herbatnik", "en": "biscuit", "category": "Żywienie"},
{"pl": "chleb", "en": "bread", "category": "Żywienie"},
{"pl": "śniadanie", "en": "breakfast", "category": "Żywienie"},
{"pl": "masło", "en": "butter", "category": "Żywienie"},
{"pl": "kapusta", "en": "cabbage", "category": "Żywienie"},
{"pl": "ciasto", "en": "cake", "category": "Żywienie"},
{"pl": "węglowodany", "en": "carbohydrates", "category": "Żywienie"},
{"pl": "marchewka", "en": "carrot", "category": "Żywienie"},
{"pl": "kalafior", "en": "cauliflower", "category": "Żywienie"},
{"pl": "płatki zbożowe", "en": "cereal", "category": "Żywienie"},
{"pl": "ser", "en": "cheese", "category": "Żywienie"},
{"pl": "kurczak", "en": "chicken", "category": "Żywienie"},
{"pl": "frytki", "en": "chips", "category": "Żywienie"},
{"pl": "czekolada", "en": "chocolate", "category": "Żywienie"},
{"pl": "orzech kokosowy", "en": "coconut", "category": "Żywienie"},
{"pl": "kawa", "en": "coffee", "category": "Żywienie"},
{"pl": "coca-cola", "en": "cola", "category": "Żywienie"},
{"pl": "śmietana", "en": "cream", "category": "Żywienie"},
{"pl": "chipsy", "en": "crisps", "category": "Żywienie"},
{"pl": "rogalik", "en": "croissant", "category": "Żywienie"},
{"pl": "ogórek", "en": "cucumber", "category": "Żywienie"},
{"pl": "smakowity", "en": "delicious", "category": "Żywienie"},
{"pl": "pączek", "en": "doughnut", "category": "Żywienie"},
{"pl": "sos do sałatek", "en": "dressing", "category": "Żywienie"},
{"pl": "napój", "en": "drink", "category": "Żywienie"},
{"pl": "jajko", "en": "egg", "category": "Żywienie"},
{"pl": "tłuszcz", "en": "fat", "category": "Żywienie"},
{"pl": "błonnik", "en": "fibre", "category": "Żywienie"},
{"pl": "ryba", "en": "fish", "category": "Żywienie"},
{"pl": "napój gazowany", "en": "fizzy drink", "category": "Żywienie"},
{"pl": "mąka", "en": "flour", "category": "Żywienie"},
{"pl": "żywność, jedzenie", "en": "food", "category": "Żywienie"},
{"pl": "owoce", "en": "Fruit", "category": "Żywienie"},
{"pl": "sok owocowy", "en": "Fruit juice", "category": "Żywienie"},
{"pl": "czosnek", "en": "garlic", "category": "Żywienie"},
{"pl": "winogrono", "en": "grape", "category": "Żywienie"},
{"pl": "szynka", "en": "ham", "category": "Żywienie"},
{"pl": "lody", "en": "ice cream", "category": "Żywienie"},
{"pl": "soczysty", "en": "juicy", "category": "Żywienie"},
{"pl": "niezdrowa żywność", "en": "junk food", "category": "Żywienie"},
{"pl": "jagnięcina", "en": "lamb", "category": "Żywienie"},
{"pl": "lazania", "en": "lasagne", "category": "Żywienie"},
{"pl": "cytryna", "en": "lemon", "category": "Żywienie"},
{"pl": "sałata", "en": "lettuce", "category": "Żywienie"},
{"pl": "mango", "en": "mango", "category": "Żywienie"},
{"pl": "majonez", "en": "mayonnaise", "category": "Żywienie"},
{"pl": "mięso", "en": "meat", "category": "Żywienie"},
{"pl": "melon", "en": "melon", "category": "Żywienie"},
{"pl": "mleko", "en": "milk", "category": "Żywienie"},
{"pl": "mięso mielone", "en": "mince, mincemeat", "category": "Żywienie"},
{"pl": "grzyb", "en": "mushroom", "category": "Żywienie"},
{"pl": "orzech", "en": "nut", "category": "Żywienie"},
{"pl": "olej", "en": "oil", "category": "Żywienie"},
{"pl": "oliwa z oliwek", "en": "olive oil", "category": "Żywienie"},
{"pl": "oliwki", "en": "olives", "category": "Żywienie"},
{"pl": "omlet", "en": "omelette", "category": "Żywienie"},
{"pl": "cebula", "en": "onion", "category": "Żywienie"},
{"pl": "pomarańcza", "en": "orange", "category": "Żywienie"},
{"pl": "naleśnik", "en": "pancake", "category": "Żywienie"},
{"pl": "makaron", "en": "pasta", "category": "Żywienie"},
{"pl": "groszek", "en": "pea", "category": "Żywienie"},
{"pl": "gruszka", "en": "pear", "category": "Żywienie"},
{"pl": "papryka", "en": "pepper", "category": "Żywienie"},
{"pl": "pizza", "en": "pizza", "category": "Żywienie"},
{"pl": "wieprzowina", "en": "pork", "category": "Żywienie"},
{"pl": "ziemniaki", "en": "potato", "category": "Żywienie"},
{"pl": "krewetka", "en": "prawn, shrimp", "category": "Żywienie"},
{"pl": "białko", "en": "protein", "category": "Żywienie"},
{"pl": "ryż", "en": "rice", "category": "Żywienie"},
{"pl": "sałatka", "en": "salad", "category": "Żywienie"},
{"pl": "sól", "en": "salt", "category": "Żywienie"},
{"pl": "słony", "en": "salty", "category": "Żywienie"},
{"pl": "kanapka", "en": "sandwich", "category": "Żywienie"},
{"pl": "kiełbasa", "en": "sausage", "category": "Żywienie"},
{"pl": "zupa", "en": "soup", "category": "Żywienie"},
{"pl": "kwaśny", "en": "sour", "category": "Żywienie"},
{"pl": "ostry", "en": "spicy", "category": "Żywienie"},
{"pl": "stek", "en": "steak", "category": "Żywienie"},
{"pl": "truskawka", "en": "strawberry", "category": "Żywienie"},
{"pl": "cukier", "en": "sugar", "category": "Żywienie"},
{"pl": "słodki", "en": "sweet", "category": "Żywienie"},
{"pl": "słodycze", "en": "sweets", "category": "Żywienie"},
{"pl": "smaczny", "en": "tasty", "category": "Żywienie"},
{"pl": "herbata", "en": "tea", "category": "Żywienie"},

{"pl": "bawełna", "en": "cotton", "category": "Zakupy i usługi"},
{"pl": "skóra", "en": "leather", "category": "Zakupy i usługi"},
{"pl": "materiał", "en": "material", "category": "Zakupy i usługi"},
{"pl": "nylon", "en": "nylon", "category": "Zakupy i usługi"},
{"pl": "jedwab", "en": "silk", "category": "Zakupy i usługi"},
{"pl": "wełna", "en": "wool", "category": "Zakupy i usługi"},
{"pl": "reklama", "en": "advertisement", "category": "Zakupy i usługi"},
{"pl": "billboard", "en": "billboard", "category": "Zakupy i usługi"},
{"pl": "znak firmowy", "en": "brand", "category": "Zakupy i usługi"},
{"pl": "broszura reklamowa", "en": "brochure", "category": "Zakupy i usługi"},
{"pl": "kampania", "en": "campaign", "category": "Zakupy i usługi"},
{"pl": "reklama", "en": "commercial", "category": "Zakupy i usługi"},
{"pl": "ulotka reklamowa", "en": "leaflet", "category": "Zakupy i usługi"},
{"pl": "produkt", "en": "product", "category": "Zakupy i usługi"},
{"pl": "piekarnia", "en": "baker's", "category": "Zakupy i usługi"},
{"pl": "księgarnia", "en": "bookshop", "category": "Zakupy i usługi"},
{"pl": "butik", "en": "boutique", "category": "Zakupy i usługi"},
{"pl": "sklep mięsny", "en": "butcher's", "category": "Zakupy i usługi"},
{"pl": "warzywniak", "en": "greengrocer's", "category": "Zakupy i usługi"},
{"pl": "kiosk", "en": "kiosk", "category": "Zakupy i usługi"},
{"pl": "bazar,targ", "en": "market", "category": "Zakupy i usługi"},
{"pl": "apteka", "en": "pharmacy, chemist's", "category": "Zakupy i usługi"},
{"pl": "sklep", "en": "shop", "category": "Zakupy i usługi"},
{"pl": "sklep z ubraniami", "en": "clothes shop", "category": "Zakupy i usługi"},
{"pl": "sklep komputerowy", "en": "computer shop", "category": "Zakupy i usługi"},
{"pl": "sklep elektryczny", "en": "electrical shop", "category": "Zakupy i usługi"},
{"pl": "jubiler", "en": "jewellery shop", "category": "Zakupy i usługi"},
{"pl": "muzyczny", "en": "music shop", "category": "Zakupy i usługi"},
{"pl": "sklep zoologiczny", "en": "pet shop", "category": "Zakupy i usługi"},
{"pl": "sklep obuwniczy", "en": "shoe shop", "category": "Zakupy i usługi"},
{"pl": "sklep sportowy", "en": "sports shop", "category": "Zakupy i usługi"},
{"pl": "centrum handlowe", "en": "shopping centre", "category": "Zakupy i usługi"},
{"pl": "stoisko", "en": "stall", "category": "Zakupy i usługi"},
{"pl": "nie działać", "en": "be out of order", "category": "Zakupy i usługi"},
{"pl": "zepsuty", "en": "broken", "category": "Zakupy i usługi"},
{"pl": "klient", "en": "customer", "category": "Zakupy i usługi"},
{"pl": "zepsuty", "en": "damaged", "category": "Zakupy i usługi"},
{"pl": "wymiana", "en": "exchange", "category": "Zakupy i usługi"},
{"pl": "dziura", "en": "hole", "category": "Zakupy i usługi"},
{"pl": "brakować", "en": "miss", "category": "Zakupy i usługi"},
{"pl": "paragon", "en": "receipt", "category": "Zakupy i usługi"},
{"pl": "zwrot pieniędzy", "en": "refund", "category": "Zakupy i usługi"},
{"pl": "rysa", "en": "scratch", "category": "Zakupy i usługi"},
{"pl": "oddawać", "en": "take back", "category": "Zakupy i usługi"},
{"pl": "okazja", "en": "bargain", "category": "Zakupy i usługi"},
{"pl": "pożyczać", "en": "borrow", "category": "Zakupy i usługi"},
{"pl": "gotówka", "en": "cash", "category": "Zakupy i usługi"},
{"pl": "bankomat", "en": "cash machine", "category": "Zakupy i usługi"},
{"pl": "reszta", "en": "change", "category": "Zakupy i usługi"},
{"pl": "tani", "en": "cheap", "category": "Zakupy i usługi"},
{"pl": "czek", "en": "cheque", "category": "Zakupy i usługi"},
{"pl": "moneta", "en": "coin", "category": "Zakupy i usługi"},
{"pl": "kosztować", "en": "cost", "category": "Zakupy i usługi"},
{"pl": "karta kredytowa", "en": "credit card", "category": "Zakupy i usługi"},
{"pl": "waluta", "en": "currency", "category": "Zakupy i usługi"},
{"pl": "zniżka", "en": "discount", "category": "Zakupy i usługi"},
{"pl": "zarabiać", "en": "earn", "category": "Zakupy i usługi"},
{"pl": "drogi", "en": "expensive", "category": "Zakupy i usługi"},
{"pl": "połowa ceny", "en": "half-price", "category": "Zakupy i usługi"},
{"pl": "ile", "en": "how much", "category": "Zakupy i usługi"},
{"pl": "pożyczać", "en": "lend", "category": "Zakupy i usługi"},
{"pl": "pieniądze", "en": "money", "category": "Zakupy i usługi"},
{"pl": "banknot", "en": "note", "category": "Zakupy i usługi"},
{"pl": "na sprzedaż", "en": "on sale", "category": "Zakupy i usługi"},
{"pl": "spłacać", "en": "pay back", "category": "Zakupy i usługi"},
{"pl": "kieszonkowe", "en": "pocket money", "category": "Zakupy i usługi"},
{"pl": "cena", "en": "price", "category": "Zakupy i usługi"},
{"pl": "przecena, sprzedaż", "en": "sale", "category": "Zakupy i usługi"},
{"pl": "nosić", "en": "wear", "category": "Zakupy i usługi"},
{"pl": "koszulka", "en": "T-shirt", "category": "Zakupy i usługi"},
{"pl": "spodnie", "en": "trousers", "category": "Zakupy i usługi"},
{"pl": "buty sportowe", "en": "trainers", "category": "Zakupy i usługi"},
{"pl": "dres", "en": "tracksuit", "category": "Zakupy i usługi"},
{"pl": "bluzka,top", "en": "top", "category": "Zakupy i usługi"},
{"pl": "wąski,ciasny", "en": "tight", "category": "Zakupy i usługi"},
{"pl": "krawat", "en": "tie", "category": "Zakupy i usługi"},
{"pl": "bluza", "en": "sweatshirt", "category": "Zakupy i usługi"},
{"pl": "styl", "en": "style", "category": "Zakupy i usługi"},
{"pl": "skarpeta", "en": "sock", "category": "Zakupy i usługi"},
{"pl": "elegancki", "en": "smart", "category": "Zakupy i usługi"},
{"pl": "kapcie", "en": "slippers", "category": "Zakupy i usługi"},
{"pl": "spódnica", "en": "skirt", "category": "Zakupy i usługi"},
{"pl": "rozmiar", "en": "size", "category": "Zakupy i usługi"},
{"pl": "but", "en": "shoe", "category": "Zakupy i usługi"},
{"pl": "koszula", "en": "shirt", "category": "Zakupy i usługi"},
{"pl": "szalik", "en": "scarf", "category": "Zakupy i usługi"},
{"pl": "sandał", "en": "sandal", "category": "Zakupy i usługi"},
{"pl": "pierścionek", "en": "ring", "category": "Zakupy i usługi"},
{"pl": "plecak", "en": "rucksack", "category": "Zakupy i usługi"},
{"pl": "piżama", "en": "pyjamas", "category": "Zakupy i usługi"},
{"pl": "gładki", "en": "plain", "category": "Zakupy i usługi"},
{"pl": "wzór", "en": "pattern", "category": "Zakupy i usługi"},
{"pl": "kostium", "en": "outfit", "category": "Zakupy i usługi"},
{"pl": "naszyjnik", "en": "necklace", "category": "Zakupy i usługi"},
{"pl": "sweter", "en": "jumper", "category": "Zakupy i usługi"},
{"pl": "biżuteria", "en": "jewellery", "category": "Zakupy i usługi"},
{"pl": "marynarka,żakiet", "en": "jacket", "category": "Zakupy i usługi"},
{"pl": "kapelusz", "en": "hat", "category": "Zakupy i usługi"},
{"pl": "rękawiczki", "en": "gloves", "category": "Zakupy i usługi"},
{"pl": "okulary", "en": "glasses", "category": "Zakupy i usługi"},

{"pl": "zakwaterowanie", "en": "accommodation", "category": "Podróżowanie i turystyka"},
{"pl": "wodny park rozrywki", "en": "aqua park", "category": "Podróżowanie i turystyka"},
{"pl": "galeria sztuki", "en": "art gallery", "category": "Podróżowanie i turystyka"},
{"pl": "plecak", "en": "backpack", "category": "Podróżowanie i turystyka"},
{"pl": "plaża", "en": "beach", "category": "Podróżowanie i turystyka"},
{"pl": "biwakowanie", "en": "camping", "category": "Podróżowanie i turystyka"},
{"pl": "pole biwakowe", "en": "campsite", "category": "Podróżowanie i turystyka"},
{"pl": "wspinaczka", "en": "climbing", "category": "Podróżowanie i turystyka"},
{"pl": "wieś", "en": "countryside", "category": "Podróżowanie i turystyka"},
{"pl": "rejs", "en": "cruise", "category": "Podróżowanie i turystyka"},
{"pl": "jazda na rowerze", "en": "cycling", "category": "Podróżowanie i turystyka"},
{"pl": "nurkować", "en": "dive", "category": "Podróżowanie i turystyka"},
{"pl": "uprawiać sporty wodne", "en": "do water sports", "category": "Podróżowanie i turystyka"},
{"pl": "jeść w restauracjach", "en": "eat in restaurants", "category": "Podróżowanie i turystyka"},
{"pl": "łowienie ryb", "en": "fishing", "category": "Podróżowanie i turystyka"},
{"pl": "wakacje", "en": "holiday", "category": "Podróżowanie i turystyka"},
{"pl": "urlopowicz", "en": "holidaymaker", "category": "Podróżowanie i turystyka"},
{"pl": "jazda konna", "en": "horse riding", "category": "Podróżowanie i turystyka"},
{"pl": "jazda na łyżwach", "en": "ice-skating", "category": "Podróżowanie i turystyka"},
{"pl": "samolot", "en": "plane", "category": "Podróżowanie i turystyka"},
{"pl": "lotnisko", "en": "airport", "category": "Podróżowanie i turystyka"},
{"pl": "przyloty", "en": "arrivals", "category": "Podróżowanie i turystyka"},
{"pl": "przyjeżdżać", "en": "arrive", "category": "Podróżowanie i turystyka"},
{"pl": "autobus", "en": "bus", "category": "Podróżowanie i turystyka"},
{"pl": "przystanek autobusowy", "en": "bus stop", "category": "Podróżowanie i turystyka"},
{"pl": "odwołanie", "en": "cancellation", "category": "Podróżowanie i turystyka"},
{"pl": "parking", "en": "car park", "category": "Podróżowanie i turystyka"},
{"pl": "autokar", "en": "coach", "category": "Podróżowanie i turystyka"},
{"pl": "pokład", "en": "deck", "category": "Podróżowanie i turystyka"},
{"pl": "opóźnienie", "en": "delay", "category": "Podróżowanie i turystyka"},
{"pl": "odjazdy,odloty", "en": "departures", "category": "Podróżowanie i turystyka"},
{"pl": "prom", "en": "ferry", "category": "Podróżowanie i turystyka"},
{"pl": "latać", "en": "fly", "category": "Podróżowanie i turystyka"},
{"pl": "wysiadać", "en": "get off", "category": "Podróżowanie i turystyka"},
{"pl": "gondola", "en": "gondola", "category": "Podróżowanie i turystyka"},
{"pl": "port", "en": "harbour", "category": "Podróżowanie i turystyka"},
{"pl": "helikopter", "en": "helicopter", "category": "Podróżowanie i turystyka"},
{"pl": "samochód terenowy", "en": "jeep", "category": "Podróżowanie i turystyka"},
{"pl": "podróż", "en": "journey", "category": "Podróżowanie i turystyka"},
{"pl": "lądować", "en": "land", "category": "Podróżowanie i turystyka"},
{"pl": "opuszczać", "en": "leave", "category": "Podróżowanie i turystyka"},
{"pl": "ciężarówka", "en": "lorry", "category": "Podróżowanie i turystyka"},
{"pl": "pasażer", "en": "passenger", "category": "Podróżowanie i turystyka"},
{"pl": "paszport", "en": "passport", "category": "Podróżowanie i turystyka"},
{"pl": "peron", "en": "platform", "category": "Podróżowanie i turystyka"},
{"pl": "port", "en": "port", "category": "Podróżowanie i turystyka"},
{"pl": "statek", "en": "ship", "category": "Podróżowanie i turystyka"},
{"pl": "stacja", "en": "station", "category": "Podróżowanie i turystyka"},
{"pl": "łódź podwodna", "en": "submarine", "category": "Podróżowanie i turystyka"},
{"pl": "walizka", "en": "suitcase", "category": "Podróżowanie i turystyka"},
{"pl": "wystartować", "en": "take off", "category": "Podróżowanie i turystyka"},
{"pl": "taksówka", "en": "taxi", "category": "Podróżowanie i turystyka"},
{"pl": "pociąg", "en": "train", "category": "Podróżowanie i turystyka"},
{"pl": "tramwaj", "en": "tram", "category": "Podróżowanie i turystyka"},
{"pl": "podróżować", "en": "travel", "category": "Podróżowanie i turystyka"},
{"pl": "wycieczka", "en": "trip", "category": "Podróżowanie i turystyka"},
{"pl": "pojazd", "en": "vehicle", "category": "Podróżowanie i turystyka"},
{"pl": "jacht", "en": "yacht", "category": "Podróżowanie i turystyka"},
{"pl": "pokój", "en": "room", "category": "Podróżowanie i turystyka"},
{"pl": "bilet okresowy", "en": "travel card", "category": "Podróżowanie i turystyka"},
{"pl": "aleja", "en": "avenue", "category": "Podróżowanie i turystyka"},
{"pl": "za, z tyłu", "en": "behind", "category": "Podróżowanie i turystyka"},
{"pl": "pomiędzy", "en": "between", "category": "Podróżowanie i turystyka"},
{"pl": "róg", "en": "corner", "category": "Podróżowanie i turystyka"},
{"pl": "przechodzić", "en": "cross", "category": "Podróżowanie i turystyka"},
{"pl": "iść wzdłuż", "en": "go along", "category": "Podróżowanie i turystyka"},
{"pl": "iść obok", "en": "go past", "category": "Podróżowanie i turystyka"},
{"pl": "iść prosto", "en": "go straight on", "category": "Podróżowanie i turystyka"},
{"pl": "w", "en": "in", "category": "Podróżowanie i turystyka"},
{"pl": "przed", "en": "in front of", "category": "Podróżowanie i turystyka"},
{"pl": "wewnątrz", "en": "inside", "category": "Podróżowanie i turystyka"},
{"pl": "autostrada", "en": "motorway", "category": "Podróżowanie i turystyka"},
{"pl": "blisko", "en": "near", "category": "Podróżowanie i turystyka"},
{"pl": "obok", "en": "next to", "category": "Podróżowanie i turystyka"},
{"pl": "naprzeciwko", "en": "opposite", "category": "Podróżowanie i turystyka"},
{"pl": "na zewnątrz", "en": "outside", "category": "Podróżowanie i turystyka"},
{"pl": "droga", "en": "road", "category": "Podróżowanie i turystyka"},
{"pl": "rondo", "en": "roundabout", "category": "Podróżowanie i turystyka"},
{"pl": "ulica", "en": "street", "category": "Podróżowanie i turystyka"},
{"pl": "morze", "en": "sea", "category": "Podróżowanie i turystyka"},

];

wordsEasy = [
    {"pl": "przodek", "en": "ancestor", "category": "Family"},
{"pl": "ciocia", "en": "aunt", "category": "Family"},
{"pl": "brat", "en": "brother", "category": "Family"},
{"pl": "kuzyn, kuzynka", "en": "cousin", "category": "Family"},
{"pl": "tata", "en": "dad", "category": "Family"},
{"pl": "córka", "en": "daughter", "category": "Family"},
{"pl": "rodzina", "en": "Family", "category": "Family"},
{"pl": "drzewo genealogiczne", "en": "Family tree", "category": "Family"},
{"pl": "ojciec", "en": "father", "category": "Family"},
{"pl": "pokolenie", "en": "generation", "category": "Family"},
{"pl": "dziadek", "en": "grandfather", "category": "Family"},
{"pl": "babcia", "en": "grandmother", "category": "Family"},
{"pl": "mąż", "en": "husband", "category": "Family"},
{"pl": "matka", "en": "mother", "category": "Family"},
{"pl": "mama", "en": "mum", "category": "Family"},
{"pl": "rodzic", "en": "parent", "category": "Family"},
{"pl": "krewny", "en": "relative", "category": "Family"},
{"pl": "siostra", "en": "sister", "category": "Family"},
{"pl": "syn", "en": "son", "category": "Family"},
{"pl": "bliźniak", "en": "twin", "category": "Family"},
{"pl": "wujek", "en": "uncle", "category": "Family"},
{"pl": "żona", "en": "wife", "category": "Family"},

{"pl": "owoc", "en": "Fruit", "category": "Fruit"},
{"pl": "jabłko", "en": "apple", "category": "Fruit"},
{"pl": "morela", "en": "apricot", "category": "Fruit"},
{"pl": "banan", "en": "banana", "category": "Fruit"},
{"pl": "wiśnia", "en": "cherry", "category": "Fruit"},
{"pl": "kokos", "en": "coconut", "category": "Fruit"},
{"pl": "winogrono", "en": "grape", "category": "Fruit"},
{"pl": "cytryna", "en": "lemon", "category": "Fruit"},
{"pl": "limonka", "en": "lime", "category": "Fruit"},
{"pl": "mango", "en": "mango", "category": "Fruit"},
{"pl": "melon", "en": "melon", "category": "Fruit"},
{"pl": "brzoskwinia", "en": "peach", "category": "Fruit"},
{"pl": "gruszka", "en": "pear", "category": "Fruit"},
{"pl": "ananas", "en": "pineapple", "category": "Fruit"},
{"pl": "śliwka", "en": "plum", "category": "Fruit"},
{"pl": "malina", "en": "raspberry", "category": "Fruit"},
{"pl": "truskawka", "en": "strawberry", "category": "Fruit"},
{"pl": "arbuz", "en": "watermelon", "category": "Fruit"},

{"pl": "bursztynowy", "en": "amber", "category": "Colors"},
{"pl": "beżowy", "en": "beige", "category": "Colors"},
{"pl": "czarny", "en": "black", "category": "Colors"},
{"pl": "niebieski", "en": "blue", "category": "Colors"},
{"pl": "brązowy", "en": "brown", "category": "Colors"},
{"pl": "kolor", "en": "color", "category": "Colors"},
{"pl": "kolorowy", "en": "colourful", "category": "Colors"},
{"pl": "bezbarwny", "en": "colourless", "category": "Colors"},
{"pl": "ciemny", "en": "dark", "category": "Colors"},
{"pl": "złoty", "en": "gold", "category": "Colors"},
{"pl": "zielony", "en": "green", "category": "Colors"},
{"pl": "szary", "en": "grey", "category": "Colors"},
{"pl": "jasny", "en": "light", "category": "Colors"},
{"pl": "pomarańczowy", "en": "orange", "category": "Colors"},
{"pl": "różowy", "en": "pink", "category": "Colors"},
{"pl": "czarny jak smoła", "en": "pitch black", "category": "Colors"},
{"pl": "fioletowy", "en": "purple/violet", "category": "Colors"},
{"pl": "czerwony", "en": "red", "category": "Colors"},
{"pl": "srebrny", "en": "silver", "category": "Colors"},
{"pl": "śnieżnobiały", "en": "snow-white", "category": "Colors"},
{"pl": "biały", "en": "white", "category": "Colors"},
{"pl": "żółty", "en": "yellow", "category": "Colors"},

{"pl": "liczba", "en": "number", "category": "Numbers"},
{"pl": "0", "en": "zero", "category": "Numbers"},
{"pl": "1", "en": "one", "category": "Numbers"},
{"pl": "2", "en": "two", "category": "Numbers"},
{"pl": "3", "en": "three", "category": "Numbers"},
{"pl": "4", "en": "four", "category": "Numbers"},
{"pl": "5", "en": "five", "category": "Numbers"},
{"pl": "6", "en": "six", "category": "Numbers"},
{"pl": "7", "en": "seven", "category": "Numbers"},
{"pl": "8", "en": "eight", "category": "Numbers"},
{"pl": "9", "en": "nine", "category": "Numbers"},
{"pl": "10", "en": "ten", "category": "Numbers"},
{"pl": "11", "en": "eleven", "category": "Numbers"},
{"pl": "12", "en": "twelve", "category": "Numbers"},
{"pl": "13", "en": "thirteen", "category": "Numbers"},
{"pl": "14", "en": "fourteen", "category": "Numbers"},
{"pl": "15", "en": "fifteen", "category": "Numbers"},
{"pl": "16", "en": "sixteen", "category": "Numbers"},
{"pl": "17", "en": "seventeen", "category": "Numbers"},
{"pl": "18", "en": "eighteen", "category": "Numbers"},
{"pl": "19", "en": "nineteen", "category": "Numbers"},
{"pl": "20", "en": "twenty", "category": "Numbers"},
{"pl": "30", "en": "thirty", "category": "Numbers"},
{"pl": "40", "en": "forty", "category": "Numbers"},
{"pl": "50", "en": "fifty", "category": "Numbers"},
{"pl": "60", "en": "sixty", "category": "Numbers"},
{"pl": "70", "en": "seventy", "category": "Numbers"},
{"pl": "80", "en": "eighty", "category": "Numbers"},
{"pl": "90", "en": "ninety", "category": "Numbers"},
{"pl": "100", "en": "a hundred", "category": "Numbers"},
{"pl": "1000", "en": "a thousand", "category": "Numbers"},
{"pl": "1000000", "en": "a million", "category": "Numbers"},

{"pl": "blond włosy", "en": "blonde hair", "category": "Hair"},
{"pl": "kręcone włosy", "en": "curly hai", "category": "Hair"},
{"pl": "ciemne włosy", "en": "dark hair", "category": "Hair"},
{"pl": "dredy", "en": "dreadlocks", "category": "Hair"},
{"pl": "jasne włosy", "en": "fair hai", "category": "Hair"},
{"pl": "grzywka", "en": "fringe", "category": "Hair"},
{"pl": "włosy", "en": "hair", "category": "Hair"},
{"pl": "fryzura", "en": "hairstyle", "category": "Hair"},
{"pl": "długie włosy", "en": "long hai", "category": "Hair"},
{"pl": "włosy średniej długości", "en": "medium length hai", "category": "Hair"},
{"pl": "kucyk, kitka", "en": "ponytail", "category": "Hair"},
{"pl": "rude włosy", "en": "red hair", "category": "Hair"},
{"pl": "krótkie włosy", "en": "short hai", "category": "Hair"},
{"pl": "sterczące włosy", "en": "spiky hai", "category": "Hair"},
{"pl": "proste włosy", "en": "straight hair", "category": "Hair"},
{"pl": "falujące włosy", "en": "wavy hair", "category": "Hair"},

{"pl": "poniedziałek", "en": "Monday", "category": "Days of the week"},
{"pl": "wtorek", "en": "Tuesday", "category": "Days of the week"},
{"pl": "środa", "en": "Wednesday", "category": "Days of the week"},
{"pl": "czwartek", "en": "Thursday", "category": "Days of the week"},
{"pl": "piątek", "en": "Friday", "category": "Days of the week"},
{"pl": "sobota", "en": "Saturday", "category": "Days of the week"},
{"pl": "niedziela", "en": "Sunday", "category": "Days of the week"},

{"pl": "łazienka", "en": "bathroom", "category": "House"},
{"pl": "sypialnia", "en": "bedroom", "category": "House"},
{"pl": "piwnica", "en": "cellar", "category": "House"},
{"pl": "jadalnia", "en": "dining room", "category": "House"},
{"pl": "garaż", "en": "garage", "category": "House"},
{"pl": "ogród", "en": "garden", "category": "House"},
{"pl": "przedpokój", "en": "hall", "category": "House"},
{"pl": "dom", "en": "house", "category": "House"},
{"pl": "kuchnia", "en": "kitchen", "category": "House"},
{"pl": "salon", "en": "sitting room", "category": "House"},
{"pl": "schody", "en": "stairs", "category": "House"},
{"pl": "toaleta", "en": "toilet", "category": "House"},

]


wordsEasyOld = [{"pl":"okno", "en":"window"},{"pl":"drzwi", "en":"door"}, {"pl": "niebieski", "en": "blue"}, {"pl": "zielony", "en": "green"}, {"pl": "czerwony", "en": "red"}, {"pl": "żółty", "en": "yellow"}, {"pl": "plecak", "en": "bag"}, {"pl": "książka", "en": "book"}, {"pl": "kredka", "en": "crayon"}, {"pl": "długopis", "en": "pen"}, {"pl": "ołówek", "en": "pencil"}, {"pl": "piórnik", "en": "pencil case"}, {"pl": "gumka", "en": "rubber"}, {"pl": "linijka", "en": "ruler"}, {"pl": "uszy", "en": "ears"}, {"pl": "oczy", "en": "eyes"}, {"pl": "twarz", "en": "face"}, {"pl": "włosy", "en": "hair"}, {"pl": "usta", "en": "mouth"}, {"pl": "nos", "en": "nose"}, {"pl": "brązowy", "en": "brown"}, {"pl": "pomarańczowy", "en": "orange"}, {"pl": "różowy", "en": "pink"}, {"pl": "fioletowy", "en": "purple"}, {"pl": "wesoły", "en": "happy"}, {"pl": "smutny", "en": "sad"}, {"pl": "ptak", "en": "bird"}, {"pl": "słoń", "en": "elephant"}, {"pl": "żyrafa", "en": "giraffe"}, {"pl": "hipopotam", "en": "hippo"}, {"pl": "lew", "en": "lion"}, {"pl": "nosorożec", "en": "rhino"}, {"pl": "zebra", "en": "zebra"}, {"pl": "czarny", "en": "black"}, {"pl": "szary", "en": "grey"}, {"pl": "biały", "en": "white"}, {"pl": "jeden", "en": "one"}, {"pl": "dwa", "en": "two"}, {"pl": "trzy", "en": "three"}, {"pl": "cztery", "en": "four"}, {"pl": "pięć", "en": "five"}, {"pl": "łódka", "en": "boat"}, {"pl": "samochód", "en": "car"}, {"pl": "kowboj", "en": "cowboy"}, {"pl": "dinozaur", "en": "dinosaur"}, {"pl": "lalka", "en": "doll"}, {"pl": "latawiec", "en": "kite"}, {"pl": "kosmonauta", "en": "spaceman"}, {"pl": "pluszowy miś", "en": "teddy bear"}, {"pl": "pociąg", "en": "train"}, {"pl": "sześć", "en": "six"}, {"pl": "siedem", "en": "seven"}, {"pl": "osiem", "en": "eight"}, {"pl": "dziewięć", "en": "nine"}, {"pl": "dziesięć", "en": "ten"}, {"pl": "jabłka", "en": "apples"}, {"pl": "banany", "en": "bananas"}, {"pl": "chleb", "en": "bread"}, {"pl": "ciasto", "en": "cake"}, {"pl": "ser", "en": "cheese"}, {"pl": "kurczak", "en": "chicken"}, {"pl": "jajka", "en": "eggs"}, {"pl": "mięso", "en": "meat"}, {"pl": "mleko", "en": "milk"}, {"pl": "gruszki", "en": "pears"}, {"pl": "pizza", "en": "pizza"}, {"pl": "kanapki", "en": "sandwiches"}, {"pl": "spagetti", "en": "spaghetti"}, {"pl": "woda", "en": "water"}];